### ISSUE TITLE
Demo/Documentation layout bug(s)

### ISSUE THREAD

**Issue by scottaohara** [owenversteeg/min#12]
In the index.html file that's part of the repo (as well as on http://minfwk.com/) when scaling the browser down to a smaller width, the documentation runs off the side of the page, creating a horizontal scroll bar.  

If that's intended, due to the sample code being in pre tags, then disregard.

However, I don't imagine the code sample, in the Grid section, should be behaving the way it does as seen in the attached screenshot.

![screen shot 2014-01-19 at 11 42 33 am](https://f.cloud.github.com/assets/4152514/1949897/bb7a8b5a-8128-11e3-9f9e-ac454e0192f8.png)

**Comment by owenversteeg** [comment]
Done. Divs with .row class needed to have `overflow: none;` applied to them.
