### ISSUE TITLE
Input styling

### ISSUE THREAD

**Issue by owenversteeg** [owenversteeg/min#19]
Some people mentioned how they disliked the input styles. Thus, I propose a vote similar to that of the buttons.

Current style (choice A):
![Current style](http://i.imgur.com/fD5VjFP.png)

Rounded borders (choice B):
![Rounded borders](http://i.imgur.com/bcphZhk.png)

Rounded borders and a shadow (choice C):
![Rounded borders+shadow](http://i.imgur.com/IuODfb2.png)

Shadow (choice D):
![Shadow](http://i.imgur.com/mFOb2XZ.png)

Rounded borders are made with the code `.addon-front + input { 0 5px 5px 0; } textarea, input { border-radius: 5px; }` - unfortunately, we can't put a combinator inside a negation selector to save space.

A shadow is made with the code `input[type='text'], textarea { box-shadow: inset 0px 2px 2px 0px rgba(0,0,0,.075); }`

**Comment by wuqi** [comment]
A

**Comment by scottaohara** [comment]
Stick w/ A.

**Comment by owenversteeg** [comment]
I'm going to keep them as-is; if people make enough of a ruckus I might open this issue in the future.
