### ISSUE TITLE
Get min back to 995 bytes minified and gzipped.

### ISSUE THREAD

**Issue by owenversteeg** [owenversteeg/min#2]
Currently at 1114 bytes minified and gzipped.

Probably achievable by shortening of the input jumble that currently exists.

**Comment by owenversteeg** [comment]
964 as of last commit.

**Comment by owenversteeg** [comment]
With the latest commits that included the new navbar we're back up to 1162 minified and gzipped.

I'm not entirely sure how to cut out an entire 167 bytes - any ideas? My current strategy is just to go over every file with a figurative fine-tooth comb until I find something.

**Comment by owenversteeg** [comment]
We're down to 1078 with the elimination of messages. 83 to go.

**Comment by scottaohara** [comment]
making some modifications to the sass & less files to try and help out with this.

question, did you change the .btn-small to .small-btn on purpose?  just wondering because it doesn't follow the naming conventions for the other buttons anymore (btn-a, etc) and the less files were different than the sass and demo site classes which used btn-small.

also, we could rename it as btn-s or btn-sm to indicate small and remove a few characters.

I will have another pull request to review in a bit to see some of the updates i made

**Comment by scottaohara** [comment]
looking through the navbar code right now, this seems to be an area where there could be considerable condensing.

for instance, there is a new declaration for 
nav {
 background: #000;
}

but everything else requires the .navbar class to complete the styling.

should everything instead be based off the nav selector, or should the background color associated with that selector just be brought into .navbar ?

i would submit that the two be combined, and .navbar be renamed to .nav to cut down on needed characters and to keep all nav styling associated with a single selector family

**Comment by owenversteeg** [comment]
As a matter of fact, everything was combined into the .navbar class until yesterday, when I decided that it would be better to use the `nav` HTML5 element for two reasons:
- It's more semantically correct
- It enables us to use the `.container` class on the navbar, which makes it the same size as the rest of the page. This makes everything look more consistent - as a matter of fact, this also slightly reduces file size as we only do half the media queries.

Thus, the current code required to create a navbar is:

```
<nav>
    <div class="navbar container" tabindex="-1" onclick="this.focus()">
        <a class="pagename navbar-link" href="#">Min Framework</a>
        <a class="navbar-link" href="#">One</a>
        <a class="navbar-link" href="#">Two</a> 
        <a class="navbar-link" href="#">Three</a>
    </div>
</nav>
<button class="close btn small-btn">×</button>
```

However, I like the suggestion of renaming `.navbar` as `.nav` to save a few characters, and I might as well also shorten `.navbar-link`. I'm going to commit that now.

Actually, come to think of it, we can drop the `navbar-link` class altogether and just use The Magic of CSS™ to apply the relevant styles with `.navbar a`

**Comment by owenversteeg** [comment]
To further elaborate on the navbar changes - the previous navbar was a constantly-expanded navbar. This was disadvantageous because if a page has a navbar, that's the first thing someone's going to see when they visit the page - they'd have to scroll down to see the actual page.

The current navbar remedies this problem by only expanding when tapped. It has a navicon, or hamburger menu, or whatever the gods of CSS are calling it now, which when tapped on expands the menu. You can see the effect here: http://pasteht.ml/fae1R

**Comment by scottaohara** [comment]
I got the Sass version down to 995 bytes

See my latest push in the update pull request

**Comment by owenversteeg** [comment]
Woo! I did it! And we didn't even have to lose rounded corners! See 3519063
