### ISSUE TITLE
Release through Bower

### ISSUE THREAD

**Issue by bebraw** [owenversteeg/min#24]
It would be nice to have `min` available through Bower registry.

**Comment by owenversteeg** [comment]
Okay, after struggling with Bower's idiocy for an hour, `bower install min` finally works.

Warning: rant below

---

According to Bower, all repos must have a master branch that contains the latest stable version. What if they don't, like Min and several other popular repos? Well, that means that another repo has to be created and kept up to date. Groan.

That other repo is now https://github.com/minfwk/min-bower. Hopefully I remember to update it come v2.0.

**Comment by bebraw** [comment]
@owenversteeg You can avoid that issue by mirroring `master` to `gh-pages`. I've set up the following bin script for myself. You could also implement it as a git plugin I guess. Maybe a git alias would work too.

Here's the script:

``` bash
#!/bin/bash
git push
git push --tags
git push origin master:gh-pages
```

If you do this you can get rid of the other repo and keep things nice and simple. Also tags get pushed (important for Bower versioning) automatically.

**Comment by owenversteeg** [comment]
Ehh, I think I'll stick with the structure I have. First of all, I don't want to add a master branch, second of all, if I edit something using the web interface the script won't work, and finally, Min is structured in such a way that the gh-pages branch is unstable; the tagged releases are the stable versions. Thus, if I mirror gh-pages and master Bower still won't work correctly. Thanks anyway though.

**Comment by bebraw** [comment]
> Ehh, I think I'll stick with the structure I have. First of all, I don't want to add a master branch, second of all, if I edit something using the web interface the script won't work, and finally, Min is structured in such a way that the gh-pages branch is unstable; the tagged releases are the stable versions. Thus, if I mirror gh-pages and master Bower still won't work correctly. Thanks anyway though.

Sure, no problems. :)
