### ISSUE TITLE
Update Sass version to include changes from LESS version

### ISSUE THREAD

**Issue by owenversteeg** [owenversteeg/min#27]
Min's LESS part is at the point where I can tag it as 2.0 and :shipit: shipit, but the Sass version is still stuck in the dark ages in many places. 

I'll do what I can now, but since Sass is more your specialty I think you (@scottaohara) should also take a look at it.

**Comment by scottaohara** [comment]
Sounds good. I'll take a look at this asap

**Comment by owenversteeg** [comment]
Merging in #29 closes this, yay!
