### ISSUE TITLE
Final browser testing

### ISSUE THREAD

**Issue by owenversteeg** [owenversteeg/min#28]
As I'm discovering (thanks partially to @cvrebert) Min may have a few browser/OS bugs still left to work out. Hopefully #26 was the last, but I'll be checking on different platforms with the help of @saucelabs and their generous donation of an unlimited Sauce account.

**Comment by owenversteeg** [comment]
Full support:
- Ubuntu 12.10 Chrome 29
- iOS 7.1 iPhone Safari
- Ubuntu Opera 12
- Android 4.0 Default Browser
- Android 4.0 Firefox 5.0
- OSX Mavericks Firefox 30
- Win8 Firefox 30
- Win7 Firefox 25
- iOS 7.1 iPad Safari
- iOS 4.3 iPad Safari
- iOS 4.3 iPhone Safari
- OSX Mountain Lion Safari 6
- WinXP Opera 11
- iOS 6 iPad Safari
- iOS 5 iPhone Safari
- Win8.1 IE11
- Win8 IE10
- Win8.1 Chrome 36
- Win8.1 Chrome 26
- Win8.1 Opera 10
- Win8.1 FF 3.6
- Android 4.2 Default Browser
- Win7 IE9
- iOS 5.1 iPhone Safari
- iOS 5 iPhone Safari

Because it lacks the focus function, Android 2.3 Default Browser (and lower) don't support Min navbars when collapsed. Thankfully this is about 5% of Android devices and lowering each year.

Partial support:
- Win8.1 Opera 9

Minor visual quibbles:
- Opera Mobile 4.5 - navbars have a minor problem as Opera Mini has a restriction on font size
- Opera Mobile 12 - inputs have a larger border than normal

Min degrades extremely gracefully in Opera 3.

Docs bug:
- FIXED ~~iOS 6+ iPhone: Download button on homepage spills over~~
- FIXED ~~iOS 6+ iPhone: Inputs have rounded borders~~
- FIXED ~~IE6/7/8 Page spills over~~

**Comment by owenversteeg** [comment]
OK, it seems that http://pasteht.ml/5s5S4 works pretty much everywhere. Closing.

**Comment by owenversteeg** [comment]
Might be a good idea to check if the homepage has any bugs on these platforms: http://pasteht.ml/m25fw

**Comment by cvrebert** [comment]
Where are you getting that 5% figure for Android 2.3?
https://developer.android.com/about/dashboards/index.html seems to give 13.5%

**Comment by owenversteeg** [comment]
13.5% is for all Gingerbread versions. The ones affected are about 5%. When I'm back on my other machine I'll dig through my history and see where I got 5% from.
