### ISSUE TITLE
Funky gradient on form controls in Android Firefox

### ISSUE THREAD

**Issue by cvrebert** [owenversteeg/min#30]
Probably due to the quirks mentioned in:
- https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#Gecko_notes
- https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button#Notes
- https://developer.mozilla.org/en-US/docs/Web/HTML/Element/textarea#Gecko_notes

**Comment by owenversteeg** [comment]
Hmm. I don't have an Android device - I just use the free account @Saucelabs gave me for being an open-source project. I'll try to take a look at this with Browserstack.

**Comment by owenversteeg** [comment]
Just reproduced using http://spoon.net/browsers. It's fixed and I'll push the fix soon but now for some reason there's an issue with the input height. GRAAAH. On the plus side I also found out what was causing the navbar bug on Android 2.2 default browser.

Thanks for reporting this (and all the other bugs!)
