### ISSUE TITLE
Extra 7 bytes - what do we do with them?

### ISSUE THREAD

**Issue by owenversteeg** [owenversteeg/min#37]
Currently Min is at 988 bytes (caused by removing -front from the addon-front class (it didn't make sense to have there, as addon-front can be used on the back and front of an input) and reordering some stuff) so we have 7 bytes to do something with. Any ideas?

Adding messages (from the min+ plugin) adds 20 bytes, so that's probably not feasible. Maybe add some feature from Bootstrap?

@scottaohara Any ideas?

**Comment by scottaohara** [comment]
nothing immediately comes to mind. but i'll think about this over the next few days.

**Comment by owenversteeg** [comment]
Okay, I managed to get rid of even more stuff. I eliminated 24 bytes as of now.

I've changed my avatar to a hotdog because I'm on a roll. 

A screenshot for posterity, as I'm going to have to change my avatar sometime or other: http://i.imgur.com/Dw35TTc.png

**Comment by owenversteeg** [comment]
so I'm putting messages in for sure. Unfortunately we only have one color of message, but that's OK.

Here's what messages look like now: http://i.imgur.com/k07gsH5.png

Any recommendations for color? I like this combo (of #def and #44e.) You're the real designer though, so you'd probably be better at this kind of thing. That said you don't have much to work with given that we only have a 4096 color palette (because only using hex triplets saves space) I'm not particularly attached to blue, I just thought it had a nice "message-y" feel to it.

However, I just realized that you could make one of them into a hex sextuplet if you wanted - we have two extra bytes and this would use them up exactly.

**Comment by scottaohara** [comment]
I actually like the background color of the message.

I was playing around with 59d as the left border hex.  what you think of that?

**Comment by owenversteeg** [comment]
Ooh, nice. I really like #59d.

**Comment by owenversteeg** [comment]
Okay, so I'm going to commit the changes I made and add in #59d. We still have an extra byte - enough to expand a hex triplet to a hex sextuplet if you want to change another color.  (gzip turns the extra 3 bytes into 1 extra byte.) I'm closing this though, as I'll add in messages.

**Comment by owenversteeg** [comment]
Committed - 02cf36b33f
