### ISSUE TITLE
box-sizing: border-box

### ISSUE THREAD

**Issue by bnb** [owenversteeg/min#47]
`box-sizing: border-box;` has become the industry standard because it gets the developer more precise results on the code they're working on. I don't think I've seen a boilerplate framework that doesn't use it. I just threw a min navbar into a site using 

``` CSS
*, *:before, *:after {
    box-sizing: border-box;
}
```

and the nav bar is ruined--the background doesn't strech the full length. Making the framework fully compatable with `box-sizing: border-box;` seems important in a general sense to me, as, going forward, almost all sites are going to be using it. It's an immediate turn off that Min doesn't work with it.

**Comment by owenversteeg** [comment]
Adding `box-sizing: border-box` to Min core isn't going to happen:
- IE7 and below don't support it, IE8's implementation is buggy, and IE9's implementation is inconsistent with other browsers/the spec
- Android browser's implementation is ridiculously buggy
- It needs to be prefixed in a lot of browsers
- Adding it would make Min significantly bigger
- Adding it would require adding Javascript, dropping support for a lot of browsers, or both.

However, I may make a CSS-only `box-sizing: border-box` plugin that you can add to Min at the expense of supporting some browsers (old IEs and Android) if there's enough interest. Let me know if this is something you might want.

**Comment by bnb** [comment]
Would definitely like to get that plugin. I've used `box-sizing: border-box` in a couple projects, and never want to go back.

**Comment by exside** [comment]
you could also use the .htc polyfill from https://github.com/Schepp/box-sizing-polyfill, but ya, still it's js and old Androids are also not supported I guess
