### ISSUE TITLE
Customized Download doesn't work on Firefox Latest

### ISSUE THREAD

**Issue by bnb** [owenversteeg/min#48]
When I first tried the Customized Download feature, it didn't work. I attempted several more times, and it still didn't work. I eventually had to go to IE to finagle it into working, which it did on the first try. Using Win8/FF Latest.

**Comment by fabaff** [comment]
Still not working...Firefox 44.0

**Comment by owenversteeg** [comment]
Resolved years ago by Firefox fixing their bug :)
