### ISSUE TITLE
Improve focus style

### ISSUE THREAD

**Issue by daformat** [owenversteeg/min#5]
![capture d ecran 2014-01-02 13 15 49](https://f.cloud.github.com/assets/1694893/1832098/d3dc50c2-73a7-11e3-9be7-5543070267b5.png)

Maybe that's something to consider, even if it's gonna eat a few more bytes :)

**Comment by owenversteeg** [comment]
Thanks for spotting that. It can be fixed two ways:
1) with `font-size: 0` applied to all `<a>` elements containing a button and `font-size: 40px` applied to all `<button>` elements. This causes the blue selection border to go around the button, and will probably cost a fair amount of bytes. I'll probably have to do quite a bit of refactoring to get enough free bytes to put it there.
2) we can go the other route - remove the selection border entirely with `outline: 0` and apply a focus style on hover. This will cost maybe 7 bytes minified+gzipped, which is reasonable. It looks the best, and this is also what Bootstrap does.
3) `width: auto` on the buttons - this makes the focus area rather large, but it's probably the smallest in terms of bytes used.

I'll probably take the second route, as it looks the best.

**Comment by daformat** [comment]
You're very welcome ! I would definitely go with 2, but maybe we could find a better way to indicate focus to the user. Even if it's ugly right now, it's definitely something you want to consider UX-wise. (my 2cents)

**Comment by owenversteeg** [comment]
Hmm. If we go with 2, when a button is focused it will look the same as if it's rolled-over.

**Comment by owenversteeg** [comment]
OK, I was able to get a 2 byte surplus by refactoring some stuff. This gives me a little more leeway for option 2.

**Comment by owenversteeg** [comment]
Great, it looks like changes by @scottaohara indirectly made this much easier. I'm about to fix this now.

**Comment by scottaohara** [comment]
I could still get this to reproduce.  Looks like it was partially due to the fact that there were <button> elements inside of `<a>` which is a mark-up no no.

Removing taking the `<button>` outside of the `<a>`, this issue went away.

**Comment by owenversteeg** [comment]
@scottaohara You're correct - for Min 2 there are two ways to make a button: `<button></button>` and `<a class="btn"></a>` Neither involve nesting of button elements because nesting elements in an `<a>` is (as you said) a markup no-no.
