### ISSUE TITLE
List Groups

### ISSUE THREAD

**Issue by kay-is** [owenversteeg/min#51]
I'd like to see those list-groups in min :)

http://getbootstrap.com/components/#list-group

**Comment by owenversteeg** [comment]
Hi! Although list groups will almost certainly not become part of Min core, these will certainly be supported via the Min Bootstrap plugin. (They have not been added yet, but will be) I would advise you to use that.

**Comment by kay-is** [comment]
Sad to hear. Didn't want to use the whole plugin. Also the docs claim it supports all of the Bootstrap features, but you say no?

**Comment by owenversteeg** [comment]
I'm still adding a few final features to it - list groups are one of those. It does have most Bootstrap features so far though. I'm hoping to be able to finish it up this weekend.

The docs are the docs for Min 2.0, which will be released in tandem with the complete Bootstrap plugin. Although the version of Min you see on the site is practically identical to Min 2.0, the Bootstrap plugin is a bit farther from the final version.

Sorry for all the confusion - the release of Min 2.0 will make everything make a lot more sense.
