### ISSUE TITLE
Multicolum listing?

### ISSUE THREAD

**Issue by barknezz** [owenversteeg/min#60]
Hey! Is there any way to create a multicolum listing with ul, li tags? Thanks.

**Comment by owenversteeg** [comment]
Yes, you could do something like that pretty easily as so:

```
<div class="container">
  <div class="row">
    <div class="col c4">
      <ul>
        <li>Item 1.1</li>
        <li>Item 1.2</li>
        <li>Item 1.3</li>
      </ul>
    </div>
    <div class="col c4">
      <ul>
        <li>Item 2.1</li>
        <li>Item 2.2</li>
        <li>Item 2.3</li>
      </ul>
    </div>
    <div class="col c4">
      <ul>
        <li>Item 3.1</li>
        <li>Item 3.2</li>
        <li>Item 3.3</li>
      </ul>
    </div>
  </div>
</div>
```

<img width="880" alt="Screenshot 2023-08-04 at 4 01 15 PM" src="https://github.com/owenversteeg/min/assets/1836017/f0a56cd1-aec3-4180-a507-98e80b235997">

My apologies for the super slow response :)
