### ISSUE TITLE
Redirect to mincss.com

### ISSUE THREAD

**Issue by franciscop** [owenversteeg/min#61]
Hi, I like the simplicity of the project since you commented on HN on a thread on [Picnic CSS](http://picnicss.com/). I added it to my README.md as an alternative to Picnic, but apparently it has even since changed the domain name [as per this pull request](https://github.com/picnicss/picnic/pull/83#issuecomment-195917299).

But as I search the web, there are [**many** references to minfwk.com](https://www.google.co.jp/search?client=ubuntu&channel=fs&q=minfwk.com). So it'd be appropriate to make a permanent redirect from minfwk.com to mincss.com, so future visitors to the first can reach the second. This would make the website _retro-compatible_ with the hundreds of articles on the internet that are now pointing to the wrong domain and in exchange gain a bit more of traffic that now it's ending on a 404.

Keep it up, Min CSS rocks :smile:

**Comment by owenversteeg** [comment]
Thanks! Also, "invasive CSS" is a fascinating idea and I'm happy to see a project out there doing it. Even though it's not really something I would use I have to say it's really cool and definitely keep up the great work. Congrats on passing 1k stars btw!

Also, as I posted in picnic/#83:

> I'm the creator of Min. The domain was changed a while back (1.5 years ago) and originally it was a 301 redirect but somehow that broke a while back. I've changed it back to a 301 which should hopefully work. Thanks for the heads-up!

The relevant issue over here is #44 (for my reference.)
