### ISSUE TITLE
The Bower version of Min and the version on the website are wildly different

### ISSUE THREAD

**Issue by riggtravis** [owenversteeg/min#62]
I'm currently using min to build a website. For previous projects using min I downloaded min myself because it was the only client side asset I needed to handle. For this project I'm using Bower because I have a bunch of client side assets. I set up my classes and stuff the same way I always did, but when I loaded up the page it looked awful.

Bower min is missing the following classes:
1. btn-close
2. btn
3. btn-sm

It also does not allow the user to give button styling to anchor links as one familiar to the min framework may be used to.

**Comment by owenversteeg** [comment]
Hey -- going through old issues and noticed this one a bit late, sorry. The version on Bower is unfortunately very out of date, which will be corrected with the release of Min 2.0 in a few days.

I'll confirm that this is actually fixed in a few days; if I forget to do this let me know. Thanks!
