### ISSUE TITLE
FR: Menu wrap rather than menu button

### ISSUE THREAD

**Issue by jimchoumobile** [owenversteeg/min#68]
I find the Menu button feature which is activated when a menu is much larger than the screen width to be problematic. 

On desktop macOS 10.12  / Safari 10.0.1:  I have to click and hold on the menu button for the menu to appear. While holding, I can't select any of the menu items. If I don't hold it the menu disappears.

On smartphone iOS 10.2 / Safari: When I click on the menu button the menu doesn't appear. If I click and hold the menu still doesn't appear.

**Comment by owenversteeg** [comment]
This affected only specific Safari releases (older and newer ones were not affected) and has not been an issue for years now; closing.
