### ISSUE TITLE
no reset?

### ISSUE THREAD

**Issue by cekvenich** [owenversteeg/min#74]
Is there a reset?
eg: https://github.com/jgthms/minireset.css/blob/master/minireset.sass

**Comment by owenversteeg** [comment]
Yes (if I understand the question properly.) Min contains a number of reset styles, for example for font, margins, background, iOS styling, tables and more. These styles, however, are integrated as part of Min and are not intended for use separately, if that's what you're asking though. Does this answer your question, or did I misunderstand?

**Comment by cekvenich** [comment]
Yeah, that is it. Love your lib. I plan to use it on our projects, both pages and custom elements/web components (since they are not affected by the page style). Thx.

**Comment by owenversteeg** [comment]
Great!

Thanks a lot for the compliments by the way, I really appreciate it. If you've got any problems with implementing Min on your site you can also email me (owenversteeg@gmail.com)
