### ISSUE TITLE
Some icons look screwy on OSX

### ISSUE THREAD

**Issue by owenversteeg** [owenversteeg/min#8]
I tested the new icons on a Mac and noticed that a few looked screwy and a few didn't show up; I remember that the keyboard icon specifically was messed up.

I'll check the icons tomorrow and see if the font-size needs to be bumped up; however, I think the Unicode font also isn't getting applied for some reason.

**Comment by nsanden** [comment]
![min](https://f.cloud.github.com/assets/2072064/1948947/adc372b8-80cb-11e3-839d-cf1c29498ad1.png)

Also in Chrome on Windows

**Comment by owenversteeg** [comment]
What you're seeing is not related to the OSX bug - but thanks for reporting it anyway. It's an issue in line 1 of buttons.less. (ico, button instead of i, button.) It'll be fixed right after the next PR.

**Comment by owenversteeg** [comment]
There are still a few that are messed-up looking. Using Arial Unicode MS fixes this somewhat.

**Comment by owenversteeg** [comment]
Arial Unicode MS: OSX 10.5+ misses ☕ (coffeecup) and ⚡ (lightning bolt)
Lucida Grande: all OSX misses ⌚ (clock) ⌛ (hourglass) ☕ (coffeecup) and ⚡ (lightning bolt)
Lucida Sans Unicode: Windows 98+ misses ⌚ (clock) ⌛ (hourglass) ☕ (coffeecup) and ⚡ (lightning bolt) 
Arial (Ubuntu): Ubuntu (unknown version) - contains everything and is the default sans-serif. Different from OSX's Arial.

Arial Unicode MS is preferable because it looks substantially nicer (at the expense of losing compatability with very old OSXes)

So, if we use `Arial Unicode MS, Lucida Sans Unicode, sans-serif` we cover OSX 10.5+, Windows 98+, and Ubuntu.

I'll commit this now.

**Comment by owenversteeg** [comment]
We can also use ✆ U+2706 TELEPHONE LOCATION SIGN and ✎ U+270E LOWER RIGHT PENCIL if we use this font combo.

**Comment by owenversteeg** [comment]
Mobile: WP7 supports Lucida Sans Unicode
iOS supports an unknown font that for some reason doesn't support ☙
